# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'nodejs-servicecon'
  appName: 'nodejs-azure-app'          
  packageDirectory: '$(System.DefaultWorkingDirectory)'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run lint
    npm run build || echo "No build script"
  displayName: 'Install dependencies'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(packageDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Archive app'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'nodejs-servicecon'
    appType: 'webAppLinux'
    appName: 'nodejs-azure-app'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
  displayName: 'Deploy to Azure Web App'
